# https://pre-commit.com/

default_stages: [ commit, push ]
default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Possible releases: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: no-commit-to-branch
        always_run: true

      - id: check-ast
        always_run: true

      - id: check-json
        always_run: true

      - id: pretty-format-json
        always_run: true
        args: [ --autofix, --indent=4 ]

      - id: check-toml
        always_run: true

      - id: check-yaml
        always_run: true
        args: [ --unsafe ]

      - id: check-xml
        always_run: true

      - id: end-of-file-fixer
        always_run: true

      - id: check-docstring-first
        always_run: true

      - id: trailing-whitespace
        exclude: .md$
        always_run: true

      - id: check-added-large-files
        always_run: true
        args: [ --maxkb=3000 ]

      - id: detect-private-key
        always_run: true

      - id: detect-aws-credentials
        always_run: false
        args: [ --allow-missing-credentials ]

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.19.1  # Possible releases: https://github.com/asottile/pyupgrade/tags
      hooks:
      -   id: pyupgrade
          args: [--py39-plus]

  - repo: https://github.com/bwhmather/ssort
    rev: 0.14.0  # Possible releases: https://github.com/bwhmather/ssort/releases
    hooks:
      - id: ssort
        entry: ssort
        always_run: false
        stages:
          - commit

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0  # Possible releases: https://github.com/pycqa/isort/releases
    hooks:
      - id: isort
        always_run: false
        name: isort (python)
        entry: isort
        args: [ --profile=black ]
        stages:
          - commit

  - repo: https://github.com/psf/black
    rev: 25.1.0  # Possible releases: https://github.com/psf/black/releases
    hooks:
      - id: black
        always_run: false
        stages:
          - commit
        args: [ --config=pyproject.toml ]


  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2  # Possible releases: https://github.com/PyCQA/flake8/releases
    hooks:
      - id: flake8
        name: flake8
        files: ^sliding_window/
        always_run: false
        additional_dependencies:
          - flake8-pyproject
          - flake8-bugbear
          - flake8-pytest-style
          - flake8-docstrings
          - flake8-import-order
          - darglint
        stages:
          - commit

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # Possible releases: https://github.com/python/mypy/tags
    hooks:
      - id: mypy
        name: mypy
        files: ^sliding_window/
        always_run: false
        args: [--config-file=pyproject.toml]
        stages:
          - commit

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        files: ^tests/
        language: system
        pass_filenames: false
        always_run: false
        stages:
          - push
